### ISSUE TITLE
Binary Link offline?

### ISSUE THREAD

**Issue by Seriousness** [imorrish/ATEMModule#1]
Thanks for all the work you already put into this. I actually planned on trying to build a test setup tonight, sadly the binarys are down and I dont know enough to build it on my own. Is there a new "latest build" folder?

**Comment by imorrish** [comment]
Thanks for wanting to try it out.
I have a compiled copy here
https://1drv.ms/u/s!ApGpqMMpRLhik5E1tVgBIJ0eq5wx2A?e=AnkyC4

**Comment by Seriousness** [comment]
Thank you! I realized it was my (or onedrives) mistake. I've had an inactive account that kept me from accessing the link!
